package:
  name: stackless
  version: '1.0'

build:
  entry_points: []
  features: []
  number: 0
  string: ''
  track_features:
    - stackless

requirements:
  build: []
  conflicts: []
  run: []

test:
  commands: []
  files: []
  imports: []
  requires: []

about:
  home: http://www.stackless.com
  license: MIT
  license_family: MIT
  license_file: '{{ RECIPE_DIR }}/LICENSE.txt'
  summary: 'meta package, which tracks the feature "stackless".'
  description: |
    stackless is a meta packages, which tracks the feature "stackless".
    If you install this package, conda will install Stackless Python instead of regular C-Python.

extra:
  recipe-maintainers:
    - akruis
